--
-- PostgreSQL database dump
--

\restrict MvAHB1xsmzdE3qqHDHdHAgmx4dl955cBMLftmPEUmehnF3P6gheKdyrCoFsqYrF

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-06-29 12:49:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16407)
-- Name: tran; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA tran;


ALTER SCHEMA tran OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 16399)
-- Name: acr_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.acr_reports (
    id bigint NOT NULL,
    accepting_officer_id bigint,
    accepting_remarks text,
    achievements text,
    agrees_with_reporting boolean,
    brief_duties text,
    employee_id bigint,
    manager_comments text,
    overall_grading character varying(255),
    property_return_date character varying(255),
    report_year character varying(255),
    reporting_officer_id bigint,
    reviewing_officer_id bigint,
    reviewing_remarks text,
    state_of_health character varying(255),
    status character varying(255),
    targets text
);


ALTER TABLE public.acr_reports OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: acr_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.acr_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acr_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16390)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    designation character varying(255),
    dob character varying(255),
    name character varying(255),
    posting character varying(255)
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16389)
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16424)
-- Name: employee_acr_details; Type: TABLE; Schema: tran; Owner: postgres
--

CREATE TABLE tran.employee_acr_details (
    _id bigint NOT NULL,
    employee_id bigint NOT NULL,
    organisation_id bigint,
    office_id bigint,
    department_id bigint,
    target text,
    achievements character varying(255),
    organization_id bigint,
    achievement character varying(255)
);


ALTER TABLE tran.employee_acr_details OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16423)
-- Name: employee_acr_details__id_seq; Type: SEQUENCE; Schema: tran; Owner: postgres
--

CREATE SEQUENCE tran.employee_acr_details__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tran.employee_acr_details__id_seq OWNER TO postgres;

--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 226
-- Name: employee_acr_details__id_seq; Type: SEQUENCE OWNED BY; Schema: tran; Owner: postgres
--

ALTER SEQUENCE tran.employee_acr_details__id_seq OWNED BY tran.employee_acr_details._id;


--
-- TOC entry 225 (class 1259 OID 16416)
-- Name: employee_acr_status; Type: TABLE; Schema: tran; Owner: postgres
--

CREATE TABLE tran.employee_acr_status (
    employee_id bigint NOT NULL,
    organization_id bigint,
    office_id bigint,
    department_id bigint,
    emp_ini_name character varying(30),
    emp_first_name character varying(100),
    emp_mid_name character varying(30),
    emp_last_name character varying(30),
    is_acr_submitted boolean DEFAULT false,
    is_notified boolean DEFAULT false,
    rating character varying(50),
    approval_status character varying(50)
);


ALTER TABLE tran.employee_acr_status OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16408)
-- Name: employee_details; Type: TABLE; Schema: tran; Owner: postgres
--

CREATE TABLE tran.employee_details (
    employee_id bigint NOT NULL,
    organization_id bigint,
    office_id bigint,
    department_id bigint,
    emp_ini_name character varying(30),
    emp_first_name character varying(100),
    emp_mid_name character varying(30),
    emp_last_name character varying(30),
    gender character varying(1),
    date_of_birth date,
    mobile_number character varying(255)
);


ALTER TABLE tran.employee_details OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16509)
-- Name: user_credentials; Type: TABLE; Schema: tran; Owner: postgres
--

CREATE TABLE tran.user_credentials (
    id bigint NOT NULL,
    employee_id bigint,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE tran.user_credentials OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16508)
-- Name: user_credentials_id_seq; Type: SEQUENCE; Schema: tran; Owner: postgres
--

CREATE SEQUENCE tran.user_credentials_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE tran.user_credentials_id_seq OWNER TO postgres;

--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 228
-- Name: user_credentials_id_seq; Type: SEQUENCE OWNED BY; Schema: tran; Owner: postgres
--

ALTER SEQUENCE tran.user_credentials_id_seq OWNED BY tran.user_credentials.id;


--
-- TOC entry 4882 (class 2604 OID 16427)
-- Name: employee_acr_details _id; Type: DEFAULT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.employee_acr_details ALTER COLUMN _id SET DEFAULT nextval('tran.employee_acr_details__id_seq'::regclass);


--
-- TOC entry 4883 (class 2604 OID 16520)
-- Name: user_credentials id; Type: DEFAULT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.user_credentials ALTER COLUMN id SET DEFAULT nextval('tran.user_credentials_id_seq'::regclass);


--
-- TOC entry 4887 (class 2606 OID 16406)
-- Name: acr_reports acr_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.acr_reports
    ADD CONSTRAINT acr_reports_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 16397)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 16441)
-- Name: employee_acr_details employee_acr_details_pkey; Type: CONSTRAINT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.employee_acr_details
    ADD CONSTRAINT employee_acr_details_pkey PRIMARY KEY (_id, employee_id);


--
-- TOC entry 4891 (class 2606 OID 16462)
-- Name: employee_acr_status employee_acr_status_pkey; Type: CONSTRAINT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.employee_acr_status
    ADD CONSTRAINT employee_acr_status_pkey PRIMARY KEY (employee_id);


--
-- TOC entry 4889 (class 2606 OID 16481)
-- Name: employee_details employee_details_pk_2; Type: CONSTRAINT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.employee_details
    ADD CONSTRAINT employee_details_pk_2 PRIMARY KEY (employee_id);


--
-- TOC entry 4895 (class 2606 OID 16519)
-- Name: user_credentials user_credentials_employee_id_key; Type: CONSTRAINT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.user_credentials
    ADD CONSTRAINT user_credentials_employee_id_key UNIQUE (employee_id);


--
-- TOC entry 4897 (class 2606 OID 16522)
-- Name: user_credentials user_credentials_pkey; Type: CONSTRAINT; Schema: tran; Owner: postgres
--

ALTER TABLE ONLY tran.user_credentials
    ADD CONSTRAINT user_credentials_pkey PRIMARY KEY (id);


-- Completed on 2026-06-29 12:49:27

--
-- PostgreSQL database dump complete
--

\unrestrict MvAHB1xsmzdE3qqHDHdHAgmx4dl955cBMLftmPEUmehnF3P6gheKdyrCoFsqYrF

